// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaIM39IDrHcVpm0wjvXjucU0rHgXqDZ6Q',
    appId: '1:458147998627:web:ead6ce704cee3f15e5c816',
    messagingSenderId: '458147998627',
    projectId: 'fir-setup-original',
    authDomain: 'fir-setup-original.firebaseapp.com',
    storageBucket: 'fir-setup-original.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaFvoAzGma9XCRwYvBRg9nyeqSI_OW5sM',
    appId: '1:458147998627:android:a732932018f14d7ce5c816',
    messagingSenderId: '458147998627',
    projectId: 'fir-setup-original',
    storageBucket: 'fir-setup-original.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQQDUxcm9_ftyDcSNuQqrqV4Y1fNZ6dDs',
    appId: '1:458147998627:ios:47cd803c518b7aa4e5c816',
    messagingSenderId: '458147998627',
    projectId: 'fir-setup-original',
    storageBucket: 'fir-setup-original.appspot.com',
    androidClientId: '458147998627-o2asua9piovpl3fpp68l9ep3j8k903n9.apps.googleusercontent.com',
    iosClientId: '458147998627-9vt67lhs5sheabvdhdsue0tbi0kk00aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSetuOriginal',
  );
}
